### ISSUE TITLE
Error during usage with maven-jar-plugin 3.0.0 (new maven-archiver component 3.0.X)

### ISSUE THREAD

**Issue by khmarbaise** [tesla/m2eclipse-mavenarchiver#8]
Error:
>     org.apache.maven.archiver.MavenArchiver.getManifest(org.apache.maven.project.MavenProject,
>     org.apache.maven.archiver.MavenArchiveConfiguration)
>     Resource: pom.xml
>     Path: /<my eclipse project>
>     Line: 1
>     Type: Maven Configuration Problem

Referencing the m2e-users list..which mentioned the m2e archive uses reflecting to use methods from maven-archiver....

**Comment by fbricon** [comment]
Please try the CI build from this p2 repo: https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.0/N/LATEST/

**Comment by trzimar** [comment]
Fix in CI build repo works, thanks!

**Comment by solomax** [comment]
Can you please guide me how this version can be installed into Eclipse?
this issue is very annoying :(

**Comment by trzimar** [comment]
Simply go to "Help/Install new software/Add repository", paste URL from fbricon comment and install it.

**Comment by solomax** [comment]
Thanks a lot!
works as expected!

**Comment by fbricon** [comment]
Since there's already a 0.17.0 "released" build and to avoid confusion, I've bumped the version to 0.17.1. https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.1/N/LATEST/ But it's really the same bits. So if you already got the latest 0.17.0 build, no need to change. It'll just make my life easier when referencing the new build at the Eclipse Foundation

**Comment by khmarbaise** [comment]
Works perfect. Thank you..

**Comment by khmarbaise** [comment]
Hm..currently have an other problem related to this:
```
Unable to read repository at http://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.0/N/LATEST/content.xml.
Unable to read repository at http://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.0/N/LATEST/content.xml.
Unable to make member of class sun.security.ssl.SSLSocketImpl accessible:  module java.base does not export sun.security.ssl to unnamed module @66f618ef
```
Seemed to be another problem?

**Comment by fbricon** [comment]
tried https?

**Comment by khmarbaise** [comment]
First tried with https..after the error i though go back to http...so another try with https:
```
Unable to read repository at https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.0/N/LATEST/content.xml.
Unable to read repository at https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.0/N/LATEST/content.xml.
Unable to make member of class sun.security.ssl.SSLSocketImpl accessible:  module java.base does not export sun.security.ssl to unnamed module @66f618ef
```
Hm. Strange i can access the site via browser ?...and using https://...

**Comment by trzimar** [comment]
Works fine with 4.6.0 Neon rc1.

**Comment by khmarbaise** [comment]
Than it must be something on my site...i will check.Thanks for your help

**Comment by krevelen** [comment]
Confirmed, works for me with Mars.2 4.5.2

**Comment by hskigithub** [comment]
Many thanks for solving this issue! Works fine for Eclipse 4.5.2 and update / install via https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.1/N/LATEST/

**Comment by fbricon** [comment]
@hskigithub  Please use https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/ instead, as another bug (#9) was introduced with maven-jar-plugin 3.0.1

**Comment by glhez** [comment]
Hello,

I also have the same problem: 
`org.apache.maven.archiver.MavenArchiver.getManifest(org.apache.maven.project.MavenProject, org.apache.maven.archiver.MavenArchiveConfiguration)`

I had the problem on all my project using maven-jar-plugin 3.0.1. 
After installing the latest from CI (0.17.2.201606141937), I only have it on one project.

The difference with other projects is the presence of a MANIFEST file (in META-INF/MANIFEST.MF): when renamed to `META-INF/MANIFESTx.MF`, the error disappear.

Note : should I create a new issue instead ?

**Comment by fbricon** [comment]
@glhez yes please open a separate issue. If you could also please attach a sample project reproducing the issue, that would really help.

**Comment by glhez** [comment]
I honestly like to do that, but I can't reproduce the bug either because it was patched, either because there was something on my side (like forgot to restart Eclipse?) that made the problem go away. 
And I also realized I did not need the MANIFEST.MF (so there was some good in that problem :)).

**Comment by ocean927** [comment]
This is pathetic. People upgrade and downgrade maven-jar-plugin in order to get rid of problem. How is it tested?

**Comment by fbricon** [comment]
@ocean927: there are some unit tests in place,. I also manually tested all maven-jar-plugin versions from 2.4 to 3.0.2 with https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/ and have not found any issues. As far as I can see 0.17.2 fixes the issue (eventually) for all the people who use it. Anyone still facing issues, should provide a sample project for us to reproduce.

**Comment by khmarbaise** [comment]
I can acknowledge that this state works with Eclipse Neon (4.6.0) with Maven Jar Plugin 3.0.2.  Thanks for fixing this.

**Comment by solomax** [comment]
Works for me as expected as well, Thanks for fixing!

**Comment by Sanne** [comment]
Hi @fbricon , just had the same issue in Hibernate OGM and also tested your link. Worked nice for me too, thanks!

I found it quite puzzling though that there's no stacktrace to be found, not even in the error log?
(And not even on stdout, as I launch Eclipse from a terminal..)

Would you have suggestion to better diagnose such an issue? It took me a while to figure out the relation to this plugin, to then find this issue.

**Comment by MarkusBarthlen** [comment]
With the same versions as @khmarbaise the problem persists for me. Can this be caused by 

`<configuration>
						<archive>
							<manifest>
								<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							</manifest>
						</archive>
					</configuration>` ?

**Comment by keepdayUp** [comment]
if i use the extensions，that will work well，why？

**Comment by svsforsuccess** [comment]
Yes it is fixed with 3.0.0 maven jar version

**Comment by gxing001** [comment]
I used this method, but I still can't solve it. I used another method to add under the POM file properties node<maven-jar-plugin.version>2.6</maven-jar-plugin.version>.   It was solved by updating the project, but when I replaced the code in gitla, this problem arose again. 
     org.apache.maven.archiver.MavenArchiver.getManifest(org.apache.maven.project.MavenProject,
org.apache.maven.archiver.MavenArchiveConfiguration)，   Now I don't know how to solve it....
